name: flavor
description: An easy way to configure flavor settings and displaying flavor banner.
version: 1.0.0
author: Stefan de Vogelaere <stefan.de.vogelaere@gmail.com>
repository: https://github/stefandevo/flutter-flavor
issue_tracker: https://github/stefandevo/flutter-flavor/issues
homepage: https://github/stefandevo/flutter-flavor

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
